name: BlockShuffle
version: '1.1.0'
main: org.lukeeirl.blockShuffle.BlockShuffle
api-version: '1.21'
authors: [ lukeeirl ]
description: A Block Shuffle game for Minecraft 1.21.5
website: lukemcd.dev

commands:
  blockshuffle:
    description: Manage the Block Shuffle game
    usage: /<command> <ready|start|stop|spectate|readyall>
    aliases: [bs]
    permission: blockshuffle.admin
    permission-message: You do not have permission to use this command.
  skipblock:
    description: Skip your assigned block once per game
    usage: /<command>
    aliases: [skip]
  lobby:
    description: Return to the lobby and leave the game
    usage: /<command>
    aliases: [l]
  testmsg:
    description: Test Adventure MiniMessage styling
    usage: /<command>
  giveskips:
    description: Give a player skips
    usage: /<command> <player> <amount>
    permission: blockshuffle.giveskips
  stats:
    description: View your game stats
    usage: /<command> <player>

permissions:
  blockshuffle.admin:
    default: true
  blockshuffle.giveskips:
    default: op