roundTimeSeconds: 300
pvpEnabled: false
decreaseTime: true
gameMode: Classic

materials:
  - AIR
  - ACACIA_LEAVES
  - ACACIA_LOG
  - ACACIA_PLANKS
  - ACACIA_PRESSURE_PLATE
  - ACACIA_SLAB
  - ACACIA_STAIRS
  - ACACIA_TRAPDOOR
  - ACACIA_WOOD
  - ACACIA_WOOD
  - ACTIVATOR_RAIL
  - AMETHYST_BLOCK
  - ANDESITE
  - ANDESITE_SLAB
  - ANDESITE_STAIRS
  - ANDESITE_WALL
  - ANVIL
  - BARREL
  - BEDROCK
  - BELL
  - BIRCH_LEAVES
  - BIRCH_LOG
  - BIRCH_PLANKS
  - BIRCH_PRESSURE_PLATE
  - BIRCH_SLAB
  - BIRCH_STAIRS
  - BIRCH_TRAPDOOR
  - BLACK_CONCRETE
  - BLACK_CONCRETE_POWDER
  - BLACK_STAINED_GLASS
  - BLACK_WOOL
  - BLAST_FURNACE
  - BLOCK_OF_COAL
  - BLOCK_OF_COPPER
  - BLOCK_OF_GOLD
  - BLOCK_OF_IRON
  - BLOCK_OF_LAPIS_LAZULI
  - RAW_COPPER_BLOCK
  - RAW_GOLD_BLOCK
  - RAW_IRON_BLOCK
  - BLOCK_OF_REDSTONE
  - BLUE_CONCRETE
  - BLUE_CONCRETE_POWDER
  - BLUE_STAINED_GLASS
  - BOOKSHELF
  - BRICK_SLAB
  - BRICK_STAIRS
  - BRICK_WALL
  - BRICKS
  - BROWN_CONCRETE
  - BROWN_CONCRETE_POWDER
  - BROWN_MUSHROOM_BLOCK
  - BROWN_STAINED_GLASS
  - BROWN_WOOL
  - BUBBLE_COLUMN
  - CACTUS
  - CAMPFIRE
  - CARTOGRAPHY_TABLE
  - CAULDRON
  - CLAY
  - CHAIN
  - CARVED_PUMPKIN
  - PUMPKIN
  - CHEST
  - COAL_BLOCK
  - COAL_ORE
  - COARSE_DIRT
  - COBBLED_DEEPSLATE
  - COBBLED_DEEPSLATE_SLAB
  - COBBLED_DEEPSLATE_STAIRS
  - COBBLED_DEEPSLATE_WALL
  - COBBLESTONE
  - COBBLESTONE_SLAB
  - COBBLESTONE_STAIRS
  - COBBLESTONE_WALL
  - COBWEB
  - COMPOSTER
  - CRAFTING_TABLE
  - CRAFTER
  - CRYING_OBSIDIAN
  - COPPER_BLOCK
  - COPPER_ORE
  - CYAN_CONCRETE
  - CYAN_CONCRETE_POWDER
  - CYAN_STAINED_GLASS
  - CYAN_WOOL
  - DARK_OAK_PLANKS
  - DARK_OAK_WOOD
  - DEEPSLATE
  - DEEPSLATE_BRICK_SLAB
  - DEEPSLATE_BRICK_STAIRS
  - DEEPSLATE_BRICK_WALL
  - DEEPSLATE_BRICKS
  - DEEPSLATE_DIAMOND_ORE
  - DEEPSLATE_GOLD_ORE
  - DEEPSLATE_IRON_ORE
  - DEEPSLATE_LAPIS_ORE
  - DEEPSLATE_REDSTONE_ORE
  - DEEPSLATE_TILE_SLAB
  - DEEPSLATE_TILE_STAIRS
  - DEEPSLATE_TILE_WALL
  - DEEPSLATE_TILES
  - DIAMOND_ORE
  - DIORITE
  - DIORITE_SLAB
  - DIORITE_STAIRS
  - DIORITE_WALL
  - DIRT
  - DIRT_PATH
  - DISPENSER
  - DRIED_KELP_BLOCK
  - DRIPSTONE_BLOCK
  - POINTED_DRIPSTONE
  - CALCITE
  - DROPPER
  - FARMLAND
  - FIRE
  - FLETCHING_TABLE
  - FLOWER_POT
  - FURNACE
  - GLASS
  - GLASS_PANE
  - GLOWSTONE
  - GOLD_ORE
  - GRANITE
  - GRANITE_SLAB
  - GRANITE_STAIRS
  - GRANITE_WALL
  - GRASS_BLOCK
  - GRAVEL
  - GRAY_CONCRETE
  - GRAY_CONCRETE_POWDER
  - GRAY_STAINED_GLASS
  - GRAY_WOOL
  - GREEN_CONCRETE
  - GREEN_CONCRETE_POWDER
  - GREEN_STAINED_GLASS
  - GREEN_WOOL
  - GRINDSTONE
  - HAY_BLOCK
  - HEAVY_WEIGHTED_PRESSURE_PLATE
  - HOPPER
  - ICE
  - IRON_BARS
  - IRON_ORE
  - IRON_TRAPDOOR
  - JUKEBOX
  - JUNGLE_LEAVES
  - JUNGLE_LOG
  - JUNGLE_PLANKS
  - JUNGLE_PRESSURE_PLATE
  - JUNGLE_SLAB
  - JUNGLE_STAIRS
  - JUNGLE_TRAPDOOR
  - JUNGLE_WOOD
  - LANTERN
  - LAPIS_ORE
  - LAVA
  - LAVA_CAULDRON
  - LECTERN
  - LIGHT_BLUE_CONCRETE
  - LIGHT_BLUE_CONCRETE_POWDER
  - LIGHT_BLUE_STAINED_GLASS
  - LIGHT_BLUE_WOOL
  - LIGHT_GRAY_CONCRETE
  - LIGHT_GRAY_CONCRETE_POWDER
  - LIGHT_GRAY_STAINED_GLASS
  - LIGHT_GRAY_WOOL
  - LIGHT_WEIGHTED_PRESSURE_PLATE
  - LIGHTNING_ROD
  - LIME_CONCRETE
  - LIME_CONCRETE_POWDER
  - LIME_STAINED_GLASS
  - LIME_WOOL
  - LOOM
  - LODESTONE
  - MAGENTA_CONCRETE
  - MAGENTA_CONCRETE_POWDER
  - MAGENTA_STAINED_GLASS
  - MAGENTA_WOOL
  - MAGMA_BLOCK
  - MOSSY_COBBLESTONE
  - MUD
  - MELON
  - NETHERRACK
  - NOTEBLOCK
  - OAK_LEAVES
  - OAK_LOG
  - OAK_PLANKS
  - OAK_PRESSURE_PLATE
  - OAK_SLAB
  - OAK_STAIRS
  - OAK_TRAPDOOR
  - OAK_WOOD
  - OBSIDIAN
  - ORANGE_CONCRETE
  - ORANGE_CONCRETE_POWDER
  - ORANGE_STAINED_GLASS
  - ORANGE_WOOL
  - PINK_CONCRETE
  - PINK_CONCRETE_POWDER
  - PINK_STAINED_GLASS
  - PINK_WOOL
  - PISTON
  - POWERED_RAIL
  - PURPLE_CONCRETE
  - PURPLE_CONCRETE_POWDER
  - PURPLE_STAINED_GLASS
  - PURPLE_WOOL
  - RAIL
  - RED_CONCRETE
  - RED_CONCRETE_POWDER
  - RED_STAINED_GLASS
  - RED_WOOL
  - REDSTONE_ORE
  - REDSTONE_TORCH
  - REDSTONE_WIRE
  - SAND
  - SANDSTONE
  - SANDSTONE_SLAB
  - SANDSTONE_STAIRS
  - SANDSTONE_WALL
  - SMITHING_TABLE
  - SMOKER
  - SPRUCE_DOOR
  - SPRUCE_FENCE
  - SPRUCE_FENCE_GATE
  - SPRUCE_LEAVES
  - SPRUCE_LOG
  - SPRUCE_PLANKS
  - SPRUCE_PRESSURE_PLATE
  - SPRUCE_SLAB
  - SPRUCE_STAIRS
  - SPRUCE_TRAPDOOR
  - SPRUCE_WOOD
  - STONE
  - STONE_BRICK_SLAB
  - STONE_BRICK_STAIRS
  - STONE_BRICKS
  - STONE_SLAB
  - STONE_STAIRS
  - STONE_BUTTON
  - STONE_PRESSURE_PLATE
  - STONECUTTER
  - SUGAR_CANE
  - SOUL_SAND
  - SOIL_SOIL
  - SOIL_FIRE
  - TORCH
  - TRAPPED_CHEST
  - TRIPWIRE
  - TRIPWIRE_HOOK
  - TUFF
  - WATER
  - WHITE_CONCRETE
  - WHITE_CONCRETE_POWDER
  - WHITE_STAINED_GLASS
  - WHITE_WOOL
  - YELLOW_CONCRETE
  - YELLOW_CONCRETE_POWDER
  - YELLOW_STAINED_GLASS
  - YELLOW_WOOL