name: block-shuffle
version: '1.0-SNAPSHOT'
main: org.lukeeirl.blockShuffle.BlockShuffle
api-version: '1.21'
authors: [ lukeeirl ]
description: A simple Block Shuffle game for Minecraft 1.21
website: lukemcd.dev

commands:
  blockshuffle:
    description: Manage the Block Shuffle game
    usage: /<command> <ready|start|stop|spectate>
    aliases: [bs]
    permission: blockshuffle.admin
    permission-message: You do not have permission to use this command.
  skipblock:
    description: Skip your assigned block once per game
    usage: /<command>


permissions:
  blockshuffle.admin:
    default: true
